import {
  AmazonIcon,
  AnthropicIcon,
  CerebrasIcon,
  CohereIcon,
  DeepInfraIcon,
  DeepSeekIcon,
  FireworksIcon,
  GoogleIcon,
  GroqIconIcon,
  InceptionIcon,
  MistralIcon,
  OpenAIIcon,
  PerplexityIcon,
  xAIIcon,
} from "./icons";

export const PROVIDER_ICONS: Record<string, typeof OpenAIIcon> = {
  openai: OpenAIIcon,
  anthropic: AnthropicIcon,
  cerebras: CerebrasIcon,
  cohere: CohereIcon,
  deepInfra: DeepInfraIcon,
  deepseek: DeepSeekIcon,
  fireworks: FireworksIcon,
  google: GoogleIcon,
  groq: GroqIconIcon,
  inception: InceptionIcon,
  mistral: MistralIcon,
  amazon: AmazonIcon,
  perplexity: PerplexityIcon,
  xai: xAIIcon,
};
